import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Icon from '@/components/icon'

export default function Home() {
  return (
    <>
      <Head>
        <title>Random Memes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}><Icon></Icon> RANDOM MEMES EVERY 30 SECONDS <Icon></Icon></h1>
      </main>
    </>
  )
}
